---
- name: Test nginx config
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Restart nginx
  service:
    name: nginx
    state: restarted